main: com.github.johnnyjayjay.presents.PresentPlugin
name: Presents
version: '0.1.0'

commands:
  present:
    description: "Get presents"
    usage: "/present [get|delete|config|list] <name>"
    permission: "presents.all"