main: com.github.johnnyjayjay.presents.PresentPlugin
name: Presents
version: '1.0'
api-version: '1.15'

commands:
  present:
    description: "Get presents"
    usage: "/present [get|delete|configure] <name>"